import json
import sys
from datetime import datetime, timezone
from pathlib import Path

from fpdf import FPDF

SEVERITY_COLORS = {
    "CRITICAL": (220, 53, 69),
    "HIGH":     (255, 140, 0),
    "MEDIUM":   (230, 175, 0),
    "LOW":      (40, 167, 69),
    "UNKNOWN":  (108, 117, 125),
}
HEADER_BG  = (33, 37, 41)
WHITE      = (255, 255, 255)
DARK_TEXT  = (30, 30, 30)
MUTED_TEXT = (108, 117, 125)
ROW_ODD    = (248, 249, 250)
ROW_EVEN   = (255, 255, 255)
PURPLE     = (102, 16, 242)
TEAL       = (23, 162, 184)


class TrivyPDF(FPDF):
    def header(self):
        self.set_fill_color(*HEADER_BG)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 9)
        self.cell(
            0, 7,
            "  Trivy Security Scan Report \u2014 SonarTrivy Demo Project",
            fill=True, new_x="LMARGIN", new_y="NEXT",
        )
        self.set_text_color(*DARK_TEXT)
        self.ln(2)

    def footer(self):
        self.set_y(-13)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*MUTED_TEXT)
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        self.cell(
            0, 8,
            f"Generated by Trivy   |   {ts}   |   Page {self.page_no()}",
            align="C",
        )
        self.set_text_color(*DARK_TEXT)


def safe(text: str, limit: int = 200) -> str:
    return str(text)[:limit].encode("latin-1", errors="replace").decode("latin-1")


def load_json(path: Path) -> dict:
    if not path.exists():
        print(f"[warn] {path} not found \u2014 using empty placeholder", file=sys.stderr)
        return {"Results": []}
    return json.loads(path.read_text(encoding="utf-8"))


def count_severities(results: list) -> dict:
    counts = {k: 0 for k in SEVERITY_COLORS}
    for r in results:
        for v in r.get("Vulnerabilities") or []:
            s = v.get("Severity", "UNKNOWN").upper()
            counts[s] = counts.get(s, 0) + 1
    return counts


def count_secrets(results: list) -> int:
    return sum(len(r.get("Secrets") or []) for r in results)


def count_misconfigs(results: list) -> int:
    return sum(len(r.get("Misconfigurations") or []) for r in results)


def badge(pdf: FPDF, label: str, value: int, x: float, y: float,
          color: tuple, w: float = 42):
    pdf.set_xy(x, y)
    pdf.set_fill_color(*color)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(w, 14, str(value), fill=True, align="C", border=0)
    pdf.set_xy(x, y + 14)
    pdf.set_font("Helvetica", "", 7)
    pdf.cell(w, 6, label, fill=True, align="C", border=0)
    pdf.set_text_color(*DARK_TEXT)


def section_title(pdf: FPDF, title: str):
    pdf.set_fill_color(235, 237, 242)
    pdf.set_text_color(40, 44, 80)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, f"  {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(200, 204, 212)
    pdf.line(pdf.l_margin, pdf.get_y(),
             pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(3)
    pdf.set_text_color(*DARK_TEXT)


def table_header_row(pdf: FPDF, columns: list):
    pdf.set_fill_color(*HEADER_BG)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 7)
    for label, w in columns:
        pdf.cell(w, 6, f" {safe(label)}", border=0, fill=True)
    pdf.ln()
    pdf.set_text_color(*DARK_TEXT)


def render_vuln_table(pdf: FPDF, results: list, max_per_target: int = 80):
    any_found = False
    for result in results:
        vulns = result.get("Vulnerabilities") or []
        if not vulns:
            continue
        any_found = True

        target   = safe(result.get("Target", ""), 90)
        pkg_type = safe(result.get("Type", ""), 30)

        pdf.set_fill_color(224, 228, 240)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(40, 44, 80)
        pdf.cell(
            0, 5,
            f"  {target}  [{pkg_type}]  \u2014  {len(vulns)} finding(s)",
            fill=True, new_x="LMARGIN", new_y="NEXT",
        )
        pdf.set_text_color(*DARK_TEXT)

        cols = [
            ("CVE / ID", 46), ("Package", 38), ("Severity", 22),
            ("Installed", 26), ("Fixed In", 26), ("Title", 32),
        ]
        table_header_row(pdf, cols)

        for i, v in enumerate(vulns[:max_per_target]):
            sev     = v.get("Severity", "UNKNOWN").upper()
            sev_col = SEVERITY_COLORS.get(sev, SEVERITY_COLORS["UNKNOWN"])
            row_bg  = ROW_ODD if i % 2 == 0 else ROW_EVEN

            pdf.set_fill_color(*row_bg)
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*DARK_TEXT)

            pdf.cell(46, 5, f" {safe(v.get('VulnerabilityID',''), 42)}", border=0, fill=True)
            pdf.cell(38, 5, f" {safe(v.get('PkgName',''), 34)}", border=0, fill=True)

            pdf.set_fill_color(*sev_col)
            pdf.set_font("Helvetica", "B", 7)
            pdf.set_text_color(*WHITE)
            pdf.cell(22, 5, f" {sev}", border=0, fill=True)

            pdf.set_fill_color(*row_bg)
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(*DARK_TEXT)

            pdf.cell(26, 5, f" {safe(v.get('InstalledVersion',''), 22)}", border=0, fill=True)
            pdf.cell(26, 5, f" {safe(v.get('FixedVersion',''), 22)}", border=0, fill=True)
            title = safe(v.get("Title") or v.get("Description") or "", 30)
            pdf.cell(32, 5, f" {title}", border=0, fill=True)
            pdf.ln()

        if len(vulns) > max_per_target:
            pdf.set_font("Helvetica", "I", 7)
            pdf.set_text_color(*MUTED_TEXT)
            pdf.cell(
                0, 5,
                f"  ... {len(vulns) - max_per_target} more findings omitted. See JSON artifact for the full list.",
                new_x="LMARGIN", new_y="NEXT",
            )
            pdf.set_text_color(*DARK_TEXT)
        pdf.ln(3)

    if not any_found:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*SEVERITY_COLORS["LOW"])
        pdf.cell(0, 6, "  No vulnerability findings.", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*DARK_TEXT)


def render_secrets_table(pdf: FPDF, results: list):
    rows = []
    for r in results:
        for s in r.get("Secrets") or []:
            rows.append({**s, "_file": r.get("Target", "")})

    if not rows:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*SEVERITY_COLORS["LOW"])
        pdf.cell(0, 6, "  No secrets detected.", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*DARK_TEXT)
        return

    cols = [("File", 68), ("Category", 30), ("Severity", 22), ("Rule ID", 36), ("Title", 34)]
    table_header_row(pdf, cols)

    for i, s in enumerate(rows):
        sev     = s.get("Severity", "UNKNOWN").upper()
        sev_col = SEVERITY_COLORS.get(sev, SEVERITY_COLORS["UNKNOWN"])
        row_bg  = ROW_ODD if i % 2 == 0 else ROW_EVEN

        pdf.set_fill_color(*row_bg)
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*DARK_TEXT)
        pdf.cell(68, 5, f" {safe(s['_file'], 64)}", border=0, fill=True)
        pdf.cell(30, 5, f" {safe(s.get('Category',''), 26)}", border=0, fill=True)

        pdf.set_fill_color(*sev_col)
        pdf.set_font("Helvetica", "B", 7)
        pdf.set_text_color(*WHITE)
        pdf.cell(22, 5, f" {sev}", border=0, fill=True)

        pdf.set_fill_color(*row_bg)
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*DARK_TEXT)
        pdf.cell(36, 5, f" {safe(s.get('RuleID',''), 32)}", border=0, fill=True)
        pdf.cell(34, 5, f" {safe(s.get('Title',''), 30)}", border=0, fill=True)
        pdf.ln()

    pdf.ln(3)


def render_misconfig_table(pdf: FPDF, results: list):
    rows = []
    for r in results:
        for m in r.get("Misconfigurations") or []:
            rows.append({**m, "_file": r.get("Target", "")})

    if not rows:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*SEVERITY_COLORS["LOW"])
        pdf.cell(0, 6, "  No misconfiguration findings.", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*DARK_TEXT)
        return

    cols = [("Check ID", 32), ("Severity", 22), ("Type", 30), ("Title", 66), ("File", 40)]
    table_header_row(pdf, cols)

    for i, m in enumerate(rows):
        sev     = m.get("Severity", "UNKNOWN").upper()
        sev_col = SEVERITY_COLORS.get(sev, SEVERITY_COLORS["UNKNOWN"])
        row_bg  = ROW_ODD if i % 2 == 0 else ROW_EVEN

        pdf.set_fill_color(*row_bg)
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*DARK_TEXT)
        pdf.cell(32, 5, f" {safe(m.get('ID',''), 28)}", border=0, fill=True)

        pdf.set_fill_color(*sev_col)
        pdf.set_font("Helvetica", "B", 7)
        pdf.set_text_color(*WHITE)
        pdf.cell(22, 5, f" {sev}", border=0, fill=True)

        pdf.set_fill_color(*row_bg)
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*DARK_TEXT)
        pdf.cell(30, 5, f" {safe(m.get('Type',''), 26)}", border=0, fill=True)
        pdf.cell(66, 5, f" {safe(m.get('Title',''), 62)}", border=0, fill=True)
        pdf.cell(40, 5, f" {safe(m['_file'], 36)}", border=0, fill=True)
        pdf.ln()

    pdf.ln(3)


def main():
    fs_data  = load_json(Path("trivy-fs-report.json"))
    img_data = load_json(Path("trivy-image-report.json"))

    fs_results  = fs_data.get("Results") or []
    img_results = img_data.get("Results") or []

    fs_counts  = count_severities(fs_results)
    img_counts = count_severities(img_results)

    pdf = TrivyPDF(orientation="L", format="A4")
    pdf.set_margins(10, 10, 10)
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(*DARK_TEXT)
    pdf.cell(0, 13, "Trivy Security Scan Report", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*MUTED_TEXT)
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    pdf.cell(0, 6, f"Project: SonarTrivy Demo   |   Date: {ts}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(40, 44, 80)
    pdf.cell(0, 6, "Filesystem Scan \u2014 Vulnerability Summary", new_x="LMARGIN", new_y="NEXT")

    bx, by = pdf.get_x(), pdf.get_y()
    for i, (sev, col) in enumerate([
        ("CRITICAL",  SEVERITY_COLORS["CRITICAL"]),
        ("HIGH",      SEVERITY_COLORS["HIGH"]),
        ("MEDIUM",    SEVERITY_COLORS["MEDIUM"]),
        ("LOW",       SEVERITY_COLORS["LOW"]),
        ("SECRETS",   PURPLE),
        ("MISCONFIGS",TEAL),
    ]):
        val = (fs_counts.get(sev, 0) if sev not in ("SECRETS", "MISCONFIGS")
               else count_secrets(fs_results) if sev == "SECRETS"
               else count_misconfigs(fs_results))
        badge(pdf, sev, val, bx + i * 45, by, col)
    pdf.set_y(by + 26)
    pdf.ln(6)

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(40, 44, 80)
    pdf.cell(0, 6, "Docker Image Scan \u2014 Vulnerability Summary", new_x="LMARGIN", new_y="NEXT")

    by2 = pdf.get_y()
    for i, (sev, col) in enumerate([
        ("CRITICAL",  SEVERITY_COLORS["CRITICAL"]),
        ("HIGH",      SEVERITY_COLORS["HIGH"]),
        ("MEDIUM",    SEVERITY_COLORS["MEDIUM"]),
        ("LOW",       SEVERITY_COLORS["LOW"]),
        ("SECRETS",   PURPLE),
        ("MISCONFIGS",TEAL),
    ]):
        val = (img_counts.get(sev, 0) if sev not in ("SECRETS", "MISCONFIGS")
               else count_secrets(img_results) if sev == "SECRETS"
               else count_misconfigs(img_results))
        badge(pdf, sev, val, bx + i * 45, by2, col)
    pdf.set_y(by2 + 30)

    pdf.add_page()
    section_title(pdf, "Filesystem Scan \u2014 Vulnerability Findings")
    render_vuln_table(pdf, fs_results)

    pdf.add_page()
    section_title(pdf, "Filesystem Scan \u2014 Secrets Detected")
    render_secrets_table(pdf, fs_results)

    section_title(pdf, "Filesystem Scan \u2014 Misconfiguration Findings")
    render_misconfig_table(pdf, fs_results)

    pdf.add_page()
    section_title(pdf, "Docker Image Scan \u2014 Vulnerability Findings")
    render_vuln_table(pdf, img_results, max_per_target=50)

    pdf.add_page()
    section_title(pdf, "Docker Image Scan \u2014 Secrets Detected")
    render_secrets_table(pdf, img_results)

    section_title(pdf, "Docker Image Scan \u2014 Misconfiguration Findings")
    render_misconfig_table(pdf, img_results)

    out = "trivy-report.pdf"
    pdf.output(out)
    print(f"Saved {out}")


if __name__ == "__main__":
    main()
